ENV0_STATE_ENCRYPTION_KEY=op://Private/env0_encryption_key/base64
CUSTOMER_AWS_ACCESS_KEY_ID=op://Private/env0_acme_fitness_secret_reader/username
CUSTOMER_AWS_SECRET_ACCESS_KEY=op://Private/env0_acme_fitness_secret_reader/password
AWS_SECRETS_REGION=us-west-2
